name: Run Salesforce Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Runs on the first of every month at midnight

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Update to v3

      - name: Set up Python
        uses: actions/setup-python@v4 # Update to v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Backup Script
        run: |
          python salesforce_backup.py

      - name: Upload backup to Salesforce
        run: |
          python upload_to_salesforce.py
